server:
  port: 8082

spring:
  application:
    name: anthem-resource
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8081
  cloud:
    nacos:
      discovery:
        server-addr: your-ip-address
        username: your-username
        password: your-password


logging:
  level:
    org.springframework.security: trace