server:
  port: 8081

spring:
  application:
    name: anthem-auth
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.13:18848
        username: nacos
        password: Nacos@1131
  datasource:
    hikari:
      pool-name: AnthemHikariCP
      minimum-idle: 10
      maximum-pool-size: 50
      auto-commit: true
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
    driver-class-name:  com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.100.11:13306/anthem?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: redPanda
    password: RedPanda@1131
  data:
    redis:
      database: 0
      host: 192.168.100.12
      port: 16379
      password: Redis@0131
      lettuce:
        pool:
          max-active: 50
          max-idle: 20
          min-idle: 10
          max-wait: 5000ms




#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:com/tempest/**/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.tempest.**.entity
  configuration:
   map-underscore-to-camel-case: true
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.springframework.security: trace
