server:
  port: 8080

spring:
  application:
    name: anthem-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8081
      client:
        provider:
          spring:
            issuer-uri: http://127.0.0.1:8081
            authorization-uri: ${spring.security.oauth2.client.provider.spring.issuer-uri}/oauth2/authorize
            token-uri: ${spring.security.oauth2.client.provider.spring.issuer-uri}/oauth2/token
        registration:
          oidc-client:
            # Our oidc-client needs a provider. The provider information has been registered
            # at the bottom of this configuration
            provider: spring
            # The following client-id and client-secret will be sent to the authorization server
            # We don't need to mention the client_credentials in the grant type here.
            # Note that, here the client-secret must not contain {noop} or any other encoding type mentioned.
            client-id: oidc-client
            client-secret: secret
            client-authentication-method: client_secret_basic
            # Our authorization grant type is authorization_code
            authorization-grant-type: authorization_code
            # The following redirect URL is the redirect URL definition of our client Server application.
            # It is generally the current application host address. The authorization server's redirect URL
            # definition means that this URL will be triggered when auth server redirects data to here.
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/oidc-client
            # Scopes that will be displayed for requesting in the consent page.
            # Authorization server must have equal or more scopes than these in number
            scope:
              - openid
              - profile
            # This client name will display in the login screen as social login type
            client-name: gateway-client
  cloud:
    nacos:
      discovery:
        server-addr: your-ip-address
        username: your-username
        password: your-password
    gateway:
      default-filters:
        - TokenRelay=
      discovery:
        locator:
          enabled: true
      routes:
        - id: anthem-resource
          uri: lb://anthem-resource
          predicates:
            - Path=/test/**

logging:
  level:
    org.springframework.security: trace